apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-k8s
spec:
  config:
    auth:
      disable_login_form: "false"
    log:
      mode: console
  deployment:
    metadata:
      annotations:
        secret.reloader.stakater.com/reload: "grafana-env"
    spec:
      template:
        spec:
          containers:
            - envFrom:
                - secretRef:
                    name: grafana-env
                    optional: true
              name: grafana
              volumeMounts:
                - mountPath: /var/lib/grafana
                  name: grafana
              resources:
                requests:
                  cpu: 100m
                limits:
                  memory: 512Mi
          securityContext:
            fsGroup: 472
            supplementalGroups:
              - 0
