apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/part-of: metrics-stack
  datasource:
    name: prometheus
    type: prometheus
    url: http://prometheus-operated:9090
    isDefault: true
    access: proxy
