namespace: monitoring
resources:
  - grafana-db-keycloak-capacity-planning.yaml
  - grafana-db-keycloak-troubleshooting.yaml
  - prom-sm-keycloak.yaml
labels:
  - pairs:
      app.kubernetes.io/name: keycloak
