apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-api-server-sli
spec:
  jobLabel: component
  endpoints:
    - port: https
      interval: 5s
      path: /metrics/slis
      authorization: # use the Bearer token for authorization
        type: Bearer
        credentials:
          key: token
          name: prometheus-sa-token
      scheme: https # use https
      tlsConfig: # skip the verification of the certificate
        insecureSkipVerify: true
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      # from kube-prometheus
      metricRelabelings:
        - action: drop
          regex: process_start_time_seconds
          sourceLabels:
            - __name__
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      component: apiserver-sli
      provider: kubernetes
