repos:
  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.8.1
    hooks:
      - id: betterleaks-docker
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.97.9
    hooks:
      - id: trufflehog
