apiVersion: v1
kind: Service
metadata:
  name: metallb-controller-monitor-service
  namespace: metallb-system
  labels:
    name: metallb-controller-monitor-service
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: controller
  ports:
    - name: metricshttps
      port: 9120
      targetPort: metricshttps
