#!/bin/bash
set -euf -o pipefail

# Generates prom-rule-cilium.yaml from awesome-prometheus-alerts.
#
# Cilium ships no official alerting rules upstream - only dashboards and
# ServiceMonitors - so the community rulesets are the closest thing to canonical.
# awesome-prometheus-alerts is the only source used here; the cilium-enterprise
# mixin is deliberately not supported (see README.md).
#
# Requires: curl, yq (v4)

AWESOME_URL="https://raw.githubusercontent.com/samber/awesome-prometheus-alerts/refs/heads/master/dist/rules/cilium/embedded-exporter.yml"

OUTPUT_FILE="$(dirname "$0")/prom-rule-cilium.yaml"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Downloading awesome-prometheus-alerts cilium rules..."
curl -fsSL "$AWESOME_URL" -o "$TMP_DIR/awesome.yaml"

# Flatten every upstream group into a single rules list and stamp `app: cilium`
# on each alert so Alertmanager routing can match on it.
yq -i '[.groups[].rules[]] | map(.labels.app = "cilium")' "$TMP_DIR/awesome.yaml"

# Local corrections. Upstream carries selectors that match no series on
# upstream Cilium (verified against v1.19.4 on a live cluster); without these
# the affected alerts can never fire. Re-verify when bumping Cilium.

# cilium_policy_change_total uses outcome="failure"; "fail" is only used by
# other metrics (cilium_bpf_map_ops_total, cilium_endpoint_regenerations_total).
yq -i '(.[] | select(.expr | test("cilium_policy_change_total")).expr) |=
  sub("outcome=\"fail\"", "outcome=\"failure\"")' "$TMP_DIR/awesome.yaml"

# `endpoint` on cilium_k8s_client_api_calls_total is not a Cilium label: it is
# the ServiceMonitor port name, always "metrics". Upstream selectors
# (endpoint="endpoint", endpoint!="metrics") therefore exclude every series.
yq -i '(.[] | select(.expr | test("cilium_k8s_client_api_calls_total")).expr) |=
  (sub("endpoint=\"endpoint\", ?", "") | sub("endpoint!=\"metrics\", ?", ""))' \
  "$TMP_DIR/awesome.yaml"

yq -n "
  .apiVersion = \"monitoring.coreos.com/v1\" |
  .kind = \"PrometheusRule\" |
  .metadata.name = \"cilium\" |
  .spec.groups[0].name = \"cilium-awesome\" |
  .spec.groups[0].rules = load(\"$TMP_DIR/awesome.yaml\")
" > "$TMP_DIR/rule.yaml"

{
  echo "# Generated by generate-prometheus-rule.sh - do not edit by hand."
  echo "#"
  echo "# cilium-awesome: $AWESOME_URL"
} > "$TMP_DIR/header.yaml"

cat "$TMP_DIR/header.yaml" "$TMP_DIR/rule.yaml" > "$OUTPUT_FILE"

SUMMARY="$(yq -r '[.spec.groups[] | .name + "=" + (.rules | length | tostring)] | join(", ")' \
  "$OUTPUT_FILE")"
echo "PrometheusRule written to $OUTPUT_FILE ($SUMMARY)"
