{{- if .Values.goldpinger.alerting.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: msteams-webhook-url-goldpinger
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "selector" . | nindent 4 }}
spec:
  data:
    - remoteRef:
        key: secret/msteams-webhook-url-goldpinger
        metadataPolicy: None
      secretKey: msteams-webhook-url-goldpinger
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv-shared-all
{{- end }}