{{- if .Values.goldpinger.alerting.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: goldpinger-{{ .Values.name }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "selector" . | nindent 4 }}
spec:
  groups:
  - name: goldpinger
    rules:
    - alert: goldpinger_nodes_unhealthy
      expr: sum(goldpinger_nodes_health_total{status="unhealthy"})
        BY (instance, goldpinger_instance) > 0
      for: 5m
      annotations:
        description: |
          Goldpinger instance {{ "{{" }} $labels.goldpinger_instance {{ "}}" }} has been reporting unhealthy nodes for at least 5 minutes.
        summary: Instance {{ "{{" }} $labels.instance {{ "}}" }} down
      labels:
        severity: warning
        service: goldpinger
{{- end }}