---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-secrets-webhook-metrics
spec:
  namespaceSelector:
    matchNames:
      - external-secrets
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 25s
      honorLabels: false
