apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider:
    aws:
      service: SecretsManager
      region: changeme
