apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9100
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: metrics-stack
  sessionAffinity: None
  type: ClusterIP
