apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-custom-metrics
  namespace: monitoring
data:
  custom-queries: |
    pg_settings_max_connections:
      query: "SELECT setting::int as max_connections FROM pg_settings WHERE name = 'max_connections'"
      metrics:
        - max_connections:
            usage: "GAUGE"
            description: "Maximum number of concurrent connections allowed"
    pg_stat_activity_connections:
      query: "SELECT count(*) as active_connections FROM pg_stat_activity WHERE state = 'active'"
      metrics:
        - active_connections:
            usage: "GAUGE"
            description: "Number of active connections"
