apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: msteams-webhook-url
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  data:
    - remoteRef:
        key: secret/msteams-webhook-url
      secretKey: msteams-webhook-url
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv-metrics-stack
