apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: envoy-proxy-global
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/part-of: metrics-stack
  url: https://raw.githubusercontent.com/envoyproxy/gateway/main/charts/gateway-addons-helm/dashboards/envoy-proxy-global.json
  folder: envoy-gateway
