apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  selector:
    matchLabels:
      app.kubernetes.io/name: eg
      control-plane: envoy-gateway
  endpoints:
    - port: metrics
