resources:
  - alertmanager
  - grafana
  - grafana-operator/v5.25.0
  - kube-state-metrics
  - metrics-server/v0.9.0
  - node-exporter
  - prometheus
  - prometheus-operator/v0.90.0
patches:
  - target:
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
