resources:
  - alertmanager
  - grafana
  - grafana-operator/v5.17.1
  - kube-state-metrics/v2.15.0
  - node-exporter
  - prometheus
  - metrics-server/v0.7.2
  # - prometheus-adapter/v0.12.0
  - prometheus-operator/v0.82.0
patches:
  - target:
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls

#   - path: overlays/adapter.yaml # link prometheus-adapter with our prometheus instance
