resources:
  - alertmanager
  - grafana
  - grafana-operator/v5.19.4
  - kube-state-metrics
  - node-exporter
  - prometheus
  - metrics-server/v0.8.0
  # - prometheus-adapter/v0.12.0
  - prometheus-operator/v0.85.0
patches:
  - target:
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls

#   - path: overlays/adapter.yaml # link prometheus-adapter with our prometheus instance
