apiVersion: v1
kind: Service
metadata:
  name: etcd-metrics
  namespace: kube-system
  labels:
    component: etcd
    tier: control-plane
spec:
  selector:
    component: etcd
    tier: control-plane
  ports:
    - name: metrics
      port: 2381
      targetPort: 2381
