apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: etcd
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      component: etcd
      tier: control-plane
  endpoints:
    - port: metrics
      interval: 10s
