apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: karpenter
spec:
  groups:
    - name: karpenter
      rules:
        - alert: KarpenterCanNotRegisterNewNodes
          annotations:
            description: |
              Karpenter in the nodepool {{`{{ $labels.nodepool }}`}} launched new nodes, but some of nodes did not registered in the cluster during 15 min
            summary: Problem with registering new nodes in the cluster.
          expr: sum by (karpenter_sh_nodepool) (operator_nodeclaim_status_condition_count {reason="Launched"}) - sum by (karpenter_sh_nodepool) (operator_nodeclaim_status_condition_count {reason="Registered"}) != 0
          for: 15m
          labels:
            severity: warning
            app: karpenter
        - alert: KarpenterCloudproviderErrors
          annotations:
            description: |
              Karpenter received an error during an api call to the cloud provider.
          expr: increase(karpenter_cloudprovider_errors_total[10m]) > 0
          for: 1m
          labels:
            severity: warning
            app: karpenter
        # - alert: KarpenterNodepoolAlmostFull
        #   annotations:
        #     description: |
        #       Nodepool {{`{{ $labels.nodeppol }}`}} launched {{`{{ $value }}`}}% {{`{{ $labels.resource_type }}`}} resources of the limit.
        #     summary: Nodepool almost full, you should increase limits.
        #   expr: sum by (nodepool,resource_type) (karpenter_nodepools_usage) / sum by (nodepool,resource_type) (karpenter_nodepools_limit) * 100 > 80
        #   for: 15m
        #   labels:
        #     severity: warning
        #     service: karpenter
