{
 "title": "Gateway API State / Policies",
 "tags": [
  "gateway-api",
  "gateway-api-state"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "tlspolicy",
    "label": "TLSPolicy",
    "query": {
     "query": "label_values(gatewayapi_tlspolicy_created, name)"
    }
   },
   {
    "name": "dnspolicy",
    "label": "DNSPolicy",
    "query": {
     "query": "label_values(gatewayapi_dnspolicy_created, name)"
    }
   },
   {
    "name": "ratelimitpolicy",
    "label": "RateLimitPolicy",
    "query": {
     "query": "label_values(gatewayapi_ratelimitpolicy_created, name)"
    }
   },
   {
    "name": "authpolicy",
    "label": "AuthPolicy",
    "query": {
     "query": "label_values(gatewayapi_authpolicy_created, name)"
    }
   },
   {
    "name": "backendtlspolicy",
    "label": "BackendTLSPolicy",
    "query": {
     "query": "label_values(gatewayapi_backendtlspolicy_created, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TLSPolicy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of TLSPolicy across all clusters",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(gatewayapi_tlspolicy_status{name=~\"${tlspolicy}\"})"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "stat",
   "description": "Total TLSPolicy with an Ready state",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "count(gatewayapi_tlspolicy_status{type=\"Ready\", name=~\"${tlspolicy}\"})"
    }
   ]
  },
  {
   "title": "TLSPolicy",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "gatewayapi_tlspolicy_target_info{name=~\"${tlspolicy}\"}"
    }
   ]
  },
  { "title": "DNSPolicy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of DNSPolicy across all clusters",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(gatewayapi_dnspolicy_status{name=~\"${dnspolicy}\"})"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "stat",
   "description": "Total DNSPolicy with an Ready state",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "targets": [
    {
     "expr": "count(gatewayapi_dnspolicy_status{type=\"Ready\", name=~\"${dnspolicy}\"})"
    }
   ]
  },
  {
   "title": "DNSPolicy",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 2 },
   "targets": [
    {
     "expr": "gatewayapi_dnspolicy_target_info{name=~\"${dnspolicy}\"}"
    }
   ]
  },
  { "title": "RateLimitPolicy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of RateLimitPolicy across all clusters",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(gatewayapi_ratelimitpolicy_status{name=~\"${ratelimitpolicy}\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "description": "Total RateLimitPolicy with an Available state",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "targets": [
    {
     "expr": "count(gatewayapi_ratelimitpolicy_status{type=\"Available\", name=~\"${ratelimitpolicy}\"})"
    }
   ]
  },
  {
   "title": "RateLimitPolicy",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "gatewayapi_ratelimitpolicy_target_info{name=~\"${ratelimitpolicy}\"}"
    }
   ]
  },
  { "title": "AuthPolicy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of AuthPolicy across all clusters",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(gatewayapi_authpolicy_status{name=~\"${authpolicy}\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "description": "Total AuthPolicy with an Available state",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "targets": [
    {
     "expr": "count(gatewayapi_authpolicy_status{type=\"Available\", name=~\"${authpolicy}\"})"
    }
   ]
  },
  {
   "title": "AuthPolicy",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "gatewayapi_authpolicy_target_info{name=~\"${authpolicy}\"}"
    }
   ]
  },
  { "title": "BackendTLSPolicy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "BackendTLSPolicy",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "gatewayapi_backendtlspolicy_target_info{name=~\"${backendtlspolicy}\"}"
    }
   ]
  }
 ]
}