namespace: monitoring
resources:
  - grafana-db-backendtlspolicies.yaml
  - grafana-db-gatewayclasses.yaml
  - grafana-db-gateways.yaml
  - grafana-db-grpcroutes.yaml
  - grafana-db-httproutes.yaml
  - grafana-db-tcproutes.yaml
  - grafana-db-tlsroutes.yaml
  - grafana-db-udproutes.yaml
  - prom-rule-gateway-api.yaml
labels:
  - pairs:
      app.kubernetes.io/name: gateway-api
