apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: kube-state-metrics
          volumeMounts:
            - name: gateway-api-state-metrics
              mountPath: /etc/customresourcestate
      volumes:
        - name: gateway-api-state-metrics
          configMap:
            defaultMode: 420
            name: gateway-api-state-metrics
