apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: quarkus
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/part-of: metrics-stack
  folder: "quarkus"
  grafanaCom:
    id: 14370
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "prometheus"
