---
# Source: x509-certificate-exporter/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: x509-certificate-exporter
  labels:
    helm.sh/chart: x509-certificate-exporter-3.19.1
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/instance: x509-certificate-exporter
    app.kubernetes.io/version: "3.19.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: x509-certificate-exporter
subjects:
- kind: ServiceAccount
  name: x509-certificate-exporter
  namespace: monitoring
