---
# Source: x509-certificate-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x509-certificate-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: x509-certificate-exporter-3.19.1
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/instance: x509-certificate-exporter
    app.kubernetes.io/version: "3.19.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: x509-certificate-exporter
      app.kubernetes.io/instance: x509-certificate-exporter
  replicas: 1
  template:
    metadata:
      labels:
        helm.sh/chart: x509-certificate-exporter-3.19.1
        app.kubernetes.io/name: x509-certificate-exporter
        app.kubernetes.io/instance: x509-certificate-exporter
        app.kubernetes.io/version: "3.19.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        runAsNonRoot: true
      restartPolicy: Always
      serviceAccountName: x509-certificate-exporter
      containers:
      - name: x509-certificate-exporter
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsUser: 65534
        resources:
          limits:
            cpu: 1
            memory: 150Mi
          requests:
            cpu: 20m
            memory: 20Mi
        image: docker.io/enix/x509-certificate-exporter:3.19.1
        imagePullPolicy: IfNotPresent
        args:
        - --watch-kube-secrets
        - --secret-type=kubernetes.io/tls:tls.crt
        - --max-cache-duration=300s
        - --listen-address=:9793
        ports:
        - name: metrics
          containerPort: 9793
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 3
          httpGet:
            path: /healthz
            port: metrics
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 3
          httpGet:
            path: /healthz
            port: metrics
