apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- grafana-db-x509-certificate-exporter.yaml
- prometheusrule.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml
