---
# Source: x509-certificate-exporter/templates/prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: x509-certificate-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: x509-certificate-exporter-3.19.1
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/instance: x509-certificate-exporter
    app.kubernetes.io/version: "3.19.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: metrics-stack
spec:
  groups:
  - name: x509-certificate-exporter.rules
    rules:
    - alert: 'X509ExporterReadErrors'
      expr: delta(x509_read_errors[15m]) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Increasing read errors for x509-certificate-exporter
        description: Over the last 15 minutes, this x509-certificate-exporter instance has experienced errors reading certificate files or querying the Kubernetes API. This could be caused by a misconfiguration if triggered when the exporter starts.
    - alert: 'CertificateError'
      expr: x509_cert_error > 0
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Certificate cannot be decoded
        description: Certificate could not be decoded {{if $labels.secret_name }}in Kubernetes secret "{{ $labels.secret_namespace }}/{{ $labels.secret_name }}"{{else}}at location "{{ $labels.filepath }}"{{end}}
    - alert: 'CertificateRenewal'
      expr: (x509_cert_not_after - time()) < (28 * 86400)
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Certificate should be renewed
        description: Certificate for "{{ $labels.subject_CN }}" should be renewed as it expires after {{ humanizeDuration $value }} {{if $labels.secret_name }}in Kubernetes secret "{{ $labels.secret_namespace }}/{{ $labels.secret_name }}"{{else}}at location "{{ $labels.filepath }}"{{end}}
    - alert: 'CertificateExpiration'
      expr: (x509_cert_not_after - time()) < (14 * 86400)
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: Certificate is about to expire
        description: Certificate for "{{ $labels.subject_CN }}" is about to expire after {{ humanizeDuration $value }} {{if $labels.secret_name }}in Kubernetes secret "{{ $labels.secret_namespace }}/{{ $labels.secret_name }}"{{else}}at location "{{ $labels.filepath }}"{{end}}
