---
# Source: x509-certificate-exporter/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: x509-certificate-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: x509-certificate-exporter-3.19.1
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/instance: x509-certificate-exporter
    app.kubernetes.io/version: "3.19.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: metrics-stack
  annotations:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: x509-certificate-exporter
      app.kubernetes.io/instance: x509-certificate-exporter
  endpoints:
  - port: metrics
    interval: 60s
    scrapeTimeout: 30s
    scheme: http
