---
# Source: x509-certificate-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: x509-certificate-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: x509-certificate-exporter-3.19.1
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/instance: x509-certificate-exporter
    app.kubernetes.io/version: "3.19.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9793
    targetPort: metrics
  selector:
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/instance: x509-certificate-exporter
