resources:
  - prom-sm-argocd-applicationset-controller-metrics.yaml
  - prom-sm-argocd-dex-server.yaml
  - prom-sm-argocd-metrics.yaml
  - prom-sm-argocd-notifications-controller.yaml
  - prom-sm-argocd-redis-haproxy-metrics.yaml
  - prom-sm-argocd-repo-server-metrics.yaml
  - prom-sm-argocd-server-metrics.yaml
labels:
  - pairs:
      app.kubernetes.io/name: argocd
